import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import SetUserID from "@/components/SetUserID";
import { Toaster } from "react-hot-toast";
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}  antialiased`}>
        <SidebarProvider>
          <Toaster position="top-center" reverseOrder={false} />
          <AppSidebar />
          <main className="w-full py-10 px-2 sm:px-10">
            <SidebarTrigger size={"icon"} />
            <SetUserID />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
